name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci: # <<- Nome alterado para referência
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Atualize para v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Versão atualizada
        with:
          node-version: "20.15.0"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci # <<- Prefira ci em vez de install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Run ESLint
        run: npx eslint "src/**/*.ts"
